name: Release

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-3rdparty:
    uses: ./.github/workflows/build-3rdparty.yml

  release:
    name: Release
    needs: build-3rdparty
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Download 3rdparty artifacts
        uses: actions/download-artifact@v8.0.1
        with:
          name: 3rdparty-output
          path: 3rdparty/output
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.23.0
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install npm dependencies
        run: pnpm install --frozen-lockfile

      - name: Build lib
        run: pnpm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: '${{ github.actor }}@users.noreply.github.com'
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: '${{ github.actor }}@users.noreply.github.com'
        run: pnpm release
